### ISSUE TITLE
Avisynth mt_luts to Epxr?

### ISSUE THREAD

**Issue by Selur** [AkarinVS/vapoursynth-plugin#16]
Can Avisynths
`MT_Luts(Diff, Diff, mode="med", pixels = " 0 0 1 0 -1 0 " ,  expr = " X Y - X Y - X Y - abs 1 + * X Y - abs 1 + "+THR+" 1 >= "+THR+" 0.5 ^ "+THR+" ? + / - 128 +", planes=[0])`
be expressed through Expr? (see: https://forum.doom9.org/showthread.php?t=184498 for more context)

**Comment by AkarinVS** [comment]
It's possible to write that as an Expr, though the process is a little complicated.

First, rewrite the expression AVS expr
`" X Y - X Y - X Y - abs 1 + * X Y - abs 1 + "+THR+" 1 >= "+THR+" 0.5 ^ "+THR+" ? + / - 128 +"`
into a Python f-string:
```python
f" X Y - X Y - X Y - abs 1 + * X Y - abs 1 + {THR} 1 >= {THR} 0.5 ^ {THR} ? + / - 128 +"
```

Expr's power operator is `pow` instead of `^` and uses lowercase for pixel variables, so we rewrite it again into a valid Expr:
```python
f" x y - x y - x y - abs 1 + * x y - abs 1 + {THR} 1 >= {THR} 0.5 pow {THR} ? + / - 128 +"
```

Now the hard part, we need to translate `MT_Luts` spatial expression using Expr's relative pixel accesses.

The easiest way to do this transformation is to write a new Python lambda expression (note that spatial expression is the 2nd clip `y`, so we only append the relative coordinate `[{M},{N}]` on the `y` clip:
```python
partial_expr = lambda M, N: f" x y[{M},{N}] - x y[{M},{N}] - x y[{M},{N}] - abs 1 + * x y[{M},{N}] - abs 1 + {THR} 1 >= {THR} 0.5 pow {THR} ? + / - 128 + " # note the trailing space
```
`pixels="0 0 1 0 -1 0"` means the y neighborhood is (0, 0), (1, 0), (-1, 0), so the three spatial values are
`partial_expr(0,0)`, `partial_expr(1,0)`, `partial_expr(-1,0)`.

As the mode is `"med"` or median, we will use the `sort3 drop swap drop` sequence to obtain the median value after those three expressions. The final Expr expression should be:
```python
partial_expr(0,0) + partial_expr(1,0) + partial_expr(-1,0) + "sort3 drop swap drop"
```

To put everything together, I believe the final Expr expression should be:
```python
# assume THR is a parameter already defined
partial_expr = lambda M, N: f" x y[{M},{N}] - x y[{M},{N}] - x y[{M},{N}] - abs 1 + * x y[{M},{N}] - abs 1 + {THR} 1 >= {THR} 0.5 pow {THR} ? + / - 128 + " # note the trailing space
res = core.akarin.Expr([diff, diff], [partial_expr(0,0) + partial_expr(1,0) + partial_expr(-1,0) + "sort3 drop swap drop", ""])
```

of course, because the two input clips are the same, you can further simplify it to:
```python
# assume THR is a parameter already defined
partial_expr = lambda M, N: f" x x[{M},{N}] - x x[{M},{N}] - x x[{M},{N}] - abs 1 + * x x[{M},{N}] - abs 1 + {THR} 1 >= {THR} 0.5 pow {THR} ? + / - 128 + " # note the trailing space
res = core.akarin.Expr(diff, [partial_expr(0,0) + partial_expr(1,0) + partial_expr(-1,0) + "sort3 drop swap drop", ""])
```

The expression itself can also be further simplified, but Expr is pretty good at optimizing expressions, so I didn't bother.

Hope this helps.

**Comment by Selur** [comment]
Thanks, for the detailed answer!
